version: "3.8"

services:
  jupyter:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: custom-r-notebook

    ports:
      - "8888:8888"

    volumes:
      - .:/workspace

    environment:
      JUPYTER_ENABLE_LAB: "yes"
      DOCKER_STACKS_JUPYTER_CMD: "lab"

    command:
      - start-notebook.py
      - --ServerApp.root_dir=/workspace
      - --ServerApp.default_url=/lab/tree/python/notebooks
