version: "3.8"

services:
  jupyter:
    build: .
    image: custom-r-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
